#!/bin/sh

// Source: https://github.com/MobilityLab/TransitScreen/wiki/Raspberry-Pi

unclutter &
xset -dpms
xset s off
matchbox-window-manager &
while true; do
  midori -e Fullscreen -a http://localhost:8080
done
